# Generated by Django 4.2.6 on 2025-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default='student_images/default.jpg', upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='img',
            field=models.ImageField(default='student_images/default.jpg', upload_to='instructor_images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='student_images/default.jpg', upload_to='student_images/'),
        ),
    ]
