# Generated by Django 4.2.6 on 2025-01-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_course_img_instructor_img_student_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
